name: VibeDrochka
version: 1.0.0
main: com.vibedrochka.VibeDrochkaPlugin
api-version: 1.20
author: VibeDrochka Team
description: Play videos in Minecraft using maps and item frames

commands:
  videdrochka:
    description: Play videos in Minecraft
    usage: /videdrochka <name> <url> <width> <height> [framerate]
    permission: vibedrochka.use
    permission-message: You don't have permission to use this command!

permissions:
  vibedrochka.use:
    description: Allows using the videdrochka command
    default: true